### ISSUE TITLE
[enhancement] way to turn csv file to path?

### ISSUE THREAD

**Issue by Not-AriStienfeld** [jsimpso81/WPIlibMathLabVIEW#123]
as far as I'm concerned, there isn't a block that turns csv files into path clusters. I feel like that would be pretty useful for coding pathfollowing code.

**Comment by Not-AriStienfeld** [comment]
by path clusters I'm referring to what the yellow folder under "3rd party" uses

**Comment by jsimpso81** [comment]
Thank you for your interest in the library.

There is a VI in this library that will read CSV or JSON files that are stored on the robot and create Trajectory data structure.  This allows Trajectories (Paths) that are created by PathWeaver or the LabVIEW trajectory creation utility to be copied to a robot, read by the robot (probably in the BEGIN.VI) the executed.  There is a sample robot that does this --- Sample 2 --  https://github.com/jsimpso81/WPIlibMathLabVIEW_Examples/tree/master/Robot_Sample_2_Diff_File_Traj_ODE

The VIs to read the JSON files are can be found here.    
![image](https://user-images.githubusercontent.com/60305400/213370987-7698d307-0bd2-4441-974e-9b172c723024.png)

![image](https://user-images.githubusercontent.com/60305400/213371253-6f66e4a9-5b3e-4a52-9821-eee24130fb56.png)

The JSON read routine isn't as easy to find...  

![image](https://user-images.githubusercontent.com/60305400/213371994-6775caf3-4b07-4d27-b57a-c209b73c2206.png)

![image](https://user-images.githubusercontent.com/60305400/213372137-02627170-394f-49ab-84b3-4a3da3337ba9.png)

![image](https://user-images.githubusercontent.com/60305400/213372357-f8409f35-6011-4dfb-82f6-3ba67bedd075.png)

Hope this helps.  If I interpretted your question incorrectly, please clarify.   If this solves your issue, please indicate that I can close the issue.  Thanks.

**Comment by Not-AriStienfeld** [comment]
Hi, thanks for the quick response. I'm wondering if this works with the holonomic jsons created from the 2023 path planner application (the one on the windows store). I understand the new features won't work, but will the json itself work?

**Comment by Not-AriStienfeld** [comment]
![image](https://user-images.githubusercontent.com/56319363/213463945-cbdf627d-70c0-4d78-951e-d39e46a086f6.png)
and I was mainly asking about how to use this block because I couldn't find a way to get the path as an array of clusters from the csv or json

**Comment by Not-AriStienfeld** [comment]
![image](https://user-images.githubusercontent.com/56319363/213516605-23cb3207-6575-4521-80f3-b855d8fd789b.png)
while I'm at it, I also realized that with this odometry, my y is extremely accurate, but the x is all messed up. any time I stop moving in the x direction (the modules reset to their default "0" location) the x displacement goes to 0. I'm not sure why this is.

**Comment by Not-AriStienfeld** [comment]
I fed the values back into the loop with a feedback node and it was worse...

**Comment by Not-AriStienfeld** [comment]
I got it working by negating some values I can't close it from mobile, so you are good to close it
