### ISSUE TITLE
Wrong pose rotation value of 2024 Apriltag ID 12

### ISSUE THREAD

**Issue by KimiYang951116** [jsimpso81/WPIlibMathLabVIEW#178]
![image](https://github.com/jsimpso81/WPIlibMathLabVIEW/assets/87694824/ed3dd056-2fd1-4c7d-bb65-3bbf05f768a9)
Hi, just to remind you it seems that in the VI "ApriltagFieldLayout_New2024" the quaternion rotation's w value is wrong for the ID 12 Apriltag, while the annotation seems to have the correct one.
 
Thanks for all of your effort in developing these libraries!
Kimi

**Comment by jsimpso81** [comment]
Fixed.   Closed.
